{{- if .Values.descheduler.enabled}}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cluster-kube-descheduler-operator
  namespace: {{ .Values.descheduler.namespace | default "openshift-kube-descheduler-operator" }}
spec:
  channel: stable
  installPlanApproval: {{ .Values.descheduler.approvalPlan | default .Values.global.approvalPlan }}
  name: cluster-kube-descheduler-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
{{- end}}